update Date.toLocaleString()でロケールに沿った日付表示に変更
rinsuki/quesdon pull request #8
Opened 2017-12-12 13:49 UTC by lnanase

日付表示を見やすいようにしました

![02](https://user-images.githubusercontent.com/11332152/33887902-b8228aa2-df8e-11e7-9e5c-329b1bd3fa8a.jpg)

2017-12-12 13:55 UTC, rinsuki requested changes
一桁になりうる時間や日にちのところは全部0埋めしたいです
![image](https://user-images.githubusercontent.com/6533808/33888121-73347e90-df8f-11e7-9a0c-d6e12a30596f.png)

2017-12-12 14:05 UTC, lnanase commented
jsで日付操作の関数は少々厄介なので、出直してきます。

2017-12-13 12:51 UTC, lnanase commented
```xdate.js``` を使用してformatするように致しました。

2017-12-14 06:49 UTC, rinsuki approved these changes
![image](https://user-images.githubusercontent.com/6533808/33979121-4b2fbf7e-e0e6-11e7-8793-a37df05b1fc5.png)

2017-12-14 06:49 UTC, merged